#include "protocol.hpp"
#include <windows.h>
#include <atomic>
#include <chrono>
#include <iostream>
#include <mutex>
#include <optional>
#include <thread>

namespace {
using namespace lct;
class handle { HANDLE value_{INVALID_HANDLE_VALUE}; public: handle()=default; explicit handle(HANDLE v):value_(v){} ~handle(){if(value_!=INVALID_HANDLE_VALUE&&value_!=nullptr)CloseHandle(value_);} handle(const handle&)=delete;handle&operator=(const handle&)=delete; HANDLE get()const{return value_;} bool valid()const{return value_!=INVALID_HANDLE_VALUE&&value_!=nullptr;} };
struct args { std::wstring control,audio,session; DWORD parent{}; };
args parse(int argc,wchar_t**argv){args a;for(int i=1;i+1<argc;i+=2){std::wstring k=argv[i],v=argv[i+1];if(k==L"--control-pipe")a.control=v;else if(k==L"--audio-pipe")a.audio=v;else if(k==L"--session")a.session=v;else if(k==L"--parent-pid")a.parent=std::stoul(v);else throw protocol_error("unknown argument");}if(a.control.empty()||a.audio.empty()||a.session.empty()||!a.parent)throw protocol_error("missing argument");return a;}
handle connect_pipe(const std::wstring& name,DWORD access){std::wstring path=L"\\\\.\\pipe\\"+name;auto deadline=GetTickCount64()+5000;do{HANDLE h=CreateFileW(path.c_str(),access,0,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h!=INVALID_HANDLE_VALUE)return handle(h);if(GetLastError()!=ERROR_PIPE_BUSY)Sleep(25);else WaitNamedPipeW(path.c_str(),100);}while(GetTickCount64()<deadline);throw protocol_error("pipe connection timeout");}
void read_exact(HANDLE h,std::span<std::uint8_t>b){std::size_t o=0;while(o<b.size()){DWORD n=0;if(!ReadFile(h,b.data()+o,static_cast<DWORD>(b.size()-o),&n,nullptr)||!n)throw protocol_error("pipe read failed");o+=n;}}
void write_exact(HANDLE h,std::span<const std::uint8_t>b){std::size_t o=0;while(o<b.size()){DWORD n=0;if(!WriteFile(h,b.data()+o,static_cast<DWORD>(b.size()-o),&n,nullptr)||!n)throw protocol_error("pipe write failed");o+=n;}}
struct message{envelope env;std::vector<std::uint8_t>payload;};
message read_message(HANDLE h,std::uint32_t max){std::array<std::uint8_t,envelope_size>head{};read_exact(h,head);auto e=decode_envelope(head,max);std::vector<std::uint8_t>p(e.payload_length);read_exact(h,p);return{e,std::move(p)};}
class control_writer{HANDLE h_;std::mutex lock_;std::uint64_t sequence_{};public:explicit control_writer(HANDLE h):h_(h){}void send(message_type t,std::span<const std::uint8_t>p,const guid&c={}){std::lock_guard g(lock_);envelope e{major,minor,static_cast<std::uint16_t>(t),0,static_cast<std::uint32_t>(p.size()),++sequence_,c};auto head=encode_envelope(e);write_exact(h_,head);write_exact(h_,p);}};
std::vector<std::uint8_t> hello(const guid&s,std::span<const std::uint8_t>nonce){std::vector<std::uint8_t>b;put_guid(b,s);b.insert(b.end(),nonce.begin(),nonce.end());put_i32(b,static_cast<std::int32_t>(GetCurrentProcessId()));put_u16(b,0);put_u16(b,0);put_string(b,"stage4-1.0.0",256);put_u64(b,3);return b;}
std::vector<std::uint8_t> ready(const guid&s){std::vector<std::uint8_t>b;put_guid(b,s);put_i32(b,static_cast<std::int32_t>(GetCurrentProcessId()));return b;}
std::vector<std::uint8_t> identity(const guid&w,const guid&c){std::vector<std::uint8_t>b;put_guid(b,w);put_guid(b,c);return b;}
}

int wmain(int argc,wchar_t**argv){
 try{
  auto a=parse(argc,argv);auto session=parse_guid(a.session);wchar_t nonce_text[129]{};auto n=GetEnvironmentVariableW(L"LIVE_CAPTIONS_ASR_NONCE",nonce_text,129);if(n!=64)throw protocol_error("missing nonce");auto nonce=parse_hex(std::wstring_view(nonce_text,n));SecureZeroMemory(nonce_text,sizeof(nonce_text));
  auto control=connect_pipe(a.control,GENERIC_READ|GENERIC_WRITE);auto audio=connect_pipe(a.audio,GENERIC_READ);control_writer writer(control.get());std::atomic_bool stopping=false;std::atomic_bool streaming=false;std::mutex stats_lock;stream_statistics stats{};
  handle parent(OpenProcess(SYNCHRONIZE,FALSE,a.parent));if(!parent.valid())throw protocol_error("parent monitoring unavailable");
  std::thread parent_monitor([&]{while(!stopping&&parent.valid()){auto wait=WaitForSingleObject(parent.get(),250);if(wait==WAIT_OBJECT_0){stopping=true;CancelIoEx(control.get(),nullptr);CancelIoEx(audio.get(),nullptr);break;}if(wait==WAIT_FAILED)break;}});
  guid correlation{};correlation.bytes[15]=1;auto h=hello(session,nonce);writer.send(message_type::worker_hello,h,correlation);auto accept=read_message(control.get(),maximum_control_payload);if(accept.env.type==static_cast<std::uint16_t>(message_type::host_reject))throw protocol_error("host rejected handshake");if(accept.env.type!=static_cast<std::uint16_t>(message_type::host_accept))throw protocol_error("expected host accept");std::size_t ao=0;if(get_guid(accept.payload,ao)!=session||get_u16(accept.payload,ao)!=0||get_i32(accept.payload,ao)!=16000||get_u16(accept.payload,ao)!=1||get_u16(accept.payload,ao)!=16||get_u16(accept.payload,ao)!=20||get_u32(accept.payload,ao)!=320||get_u32(accept.payload,ao)!=640||ao!=accept.payload.size())throw protocol_error("invalid host accept");auto r=ready(session);writer.send(message_type::worker_ready,r,correlation);
  std::thread audio_reader([&]{try{while(!stopping){auto m=read_message(audio.get(),audio_payload_size);if(m.env.type!=static_cast<std::uint16_t>(message_type::audio_frame))throw protocol_error("invalid audio message");auto meta=decode_audio_metadata(m.payload);std::lock_guard g(stats_lock);if(!streaming||meta.worker_session!=session||!validate_audio(stats,meta)){stats.invalid++;continue;}if(stats.frames%50==0){auto p=encode_summary(stats);writer.send(message_type::audio_progress,p);}}}catch(...){if(!stopping){stopping=true;CancelIoEx(control.get(),nullptr);}}});
  try{while(!stopping){auto m=read_message(control.get(),maximum_control_payload);auto raw=m.env.type;auto known=raw>=static_cast<std::uint16_t>(message_type::worker_hello)&&raw<=static_cast<std::uint16_t>(message_type::caption_event);if(!known){if((m.env.flags&1)!=0)continue;throw protocol_error("unknown required control message");}auto type=static_cast<message_type>(raw);if(type==message_type::ping){writer.send(message_type::pong,m.payload,m.env.correlation);continue;}if(type==message_type::start_audio){std::size_t o=0;if(get_guid(m.payload,o)!=session)throw protocol_error("worker session mismatch");stream_statistics fresh{};fresh.capture_session=get_guid(m.payload,o);auto initial=get_i64(m.payload,o);(void)get_i64(m.payload,o);if(get_i32(m.payload,o)!=16000||get_u16(m.payload,o)!=1||get_u16(m.payload,o)!=16||get_u16(m.payload,o)!=20||get_u32(m.payload,o)!=320||get_u32(m.payload,o)!=640||initial<1)throw protocol_error("invalid audio format");{std::lock_guard g(stats_lock);stats=fresh;stats.last_sequence=initial-1;}streaming=true;auto p=identity(session,fresh.capture_session);writer.send(message_type::audio_started,p,m.env.correlation);continue;}if(type==message_type::stop_audio){std::size_t o=0;if(get_guid(m.payload,o)!=session)throw protocol_error("worker session mismatch");auto capture=get_guid(m.payload,o);streaming=false;std::vector<std::uint8_t>p;{std::lock_guard g(stats_lock);if(capture!=stats.capture_session)throw protocol_error("capture session mismatch");p=encode_summary(stats);}writer.send(message_type::audio_stopped,p,m.env.correlation);continue;}if(type==message_type::shutdown){std::size_t o=0;if(get_guid(m.payload,o)!=session)throw protocol_error("worker session mismatch");writer.send(message_type::shutdown_ack,m.payload,m.env.correlation);stopping=true;CancelIoEx(audio.get(),nullptr);break;}throw protocol_error("control message is invalid in the current state");}}catch(const std::exception&e){std::vector<std::uint8_t>p;put_u16(p,0);put_string(p,e.what());try{writer.send(message_type::error,p);}catch(...){/* The control pipe is already unavailable. */}stopping=true;CancelIoEx(audio.get(),nullptr);CancelIoEx(control.get(),nullptr);if(audio_reader.joinable())audio_reader.join();if(parent_monitor.joinable())parent_monitor.join();return 21;}
  stopping=true;CancelIoEx(audio.get(),nullptr);CancelIoEx(control.get(),nullptr);if(audio_reader.joinable())audio_reader.join();if(parent_monitor.joinable())parent_monitor.join();std::cout<<"LiveCaptionsAsrWorker clean shutdown\n";return 0;
 }catch(const std::exception&e){std::cerr<<"worker failure: "<<e.what()<<"\n";return 20;}
}
