#include "protocol.hpp"
#include <algorithm>
#include <limits>

namespace lct {
namespace { void need(std::span<const std::uint8_t> b, std::size_t o, std::size_t n) { if (o > b.size() || n > b.size()-o) throw protocol_error("truncated payload"); } int hex(wchar_t c){ if(c>=L'0'&&c<=L'9')return c-L'0'; if(c>=L'a'&&c<=L'f')return c-L'a'+10; if(c>=L'A'&&c<=L'F')return c-L'A'+10; return -1; } bool valid_utf8(std::span<const std::uint8_t>b){for(std::size_t i=0;i<b.size();){auto c=b[i++];if(c<0x80)continue;std::size_t n=0;std::uint32_t code=0,min=0;if((c&0xe0)==0xc0){n=1;code=c&0x1f;min=0x80;}else if((c&0xf0)==0xe0){n=2;code=c&0x0f;min=0x800;}else if((c&0xf8)==0xf0){n=3;code=c&7;min=0x10000;}else return false;if(i+n>b.size())return false;for(std::size_t j=0;j<n;++j){auto d=b[i++];if((d&0xc0)!=0x80)return false;code=(code<<6)|(d&0x3f);}if(code<min||code>0x10ffff||(code>=0xd800&&code<=0xdfff))return false;}return true;} }
void put_u16(std::vector<std::uint8_t>& b,std::uint16_t v){b.push_back(static_cast<std::uint8_t>(v));b.push_back(static_cast<std::uint8_t>(v>>8));}
void put_u32(std::vector<std::uint8_t>& b,std::uint32_t v){for(int i=0;i<4;++i)b.push_back(static_cast<std::uint8_t>(v>>(i*8)));}
void put_i32(std::vector<std::uint8_t>& b,std::int32_t v){put_u32(b,static_cast<std::uint32_t>(v));}
void put_u64(std::vector<std::uint8_t>& b,std::uint64_t v){for(int i=0;i<8;++i)b.push_back(static_cast<std::uint8_t>(v>>(i*8)));}
void put_i64(std::vector<std::uint8_t>& b,std::int64_t v){put_u64(b,static_cast<std::uint64_t>(v));}
void put_guid(std::vector<std::uint8_t>& b,const guid& v){b.insert(b.end(),v.bytes.begin(),v.bytes.end());}
void put_string(std::vector<std::uint8_t>& b,std::string_view v,std::size_t max){if(v.size()>max)throw protocol_error("string too long");put_u32(b,static_cast<std::uint32_t>(v.size()));b.insert(b.end(),v.begin(),v.end());}
std::uint16_t get_u16(std::span<const std::uint8_t>b,std::size_t&o){need(b,o,2);auto v=static_cast<std::uint16_t>(b[o]|(b[o+1]<<8));o+=2;return v;}
std::uint32_t get_u32(std::span<const std::uint8_t>b,std::size_t&o){need(b,o,4);std::uint32_t v=0;for(int i=0;i<4;++i)v|=static_cast<std::uint32_t>(b[o+i])<<(i*8);o+=4;return v;}
std::int32_t get_i32(std::span<const std::uint8_t>b,std::size_t&o){return static_cast<std::int32_t>(get_u32(b,o));}
std::uint64_t get_u64(std::span<const std::uint8_t>b,std::size_t&o){need(b,o,8);std::uint64_t v=0;for(int i=0;i<8;++i)v|=static_cast<std::uint64_t>(b[o+i])<<(i*8);o+=8;return v;}
std::int64_t get_i64(std::span<const std::uint8_t>b,std::size_t&o){return static_cast<std::int64_t>(get_u64(b,o));}
guid get_guid(std::span<const std::uint8_t>b,std::size_t&o){need(b,o,16);guid g;std::copy_n(b.begin()+static_cast<std::ptrdiff_t>(o),16,g.bytes.begin());o+=16;return g;}
std::string get_string(std::span<const std::uint8_t>b,std::size_t&o,std::size_t max){auto n=get_u32(b,o);if(n>max)throw protocol_error("string too long");need(b,o,n);auto value=b.subspan(o,n);if(!valid_utf8(value))throw protocol_error("invalid utf8");std::string s(reinterpret_cast<const char*>(value.data()),n);o+=n;return s;}
std::array<std::uint8_t,envelope_size> encode_envelope(const envelope&e){std::vector<std::uint8_t>b;put_u32(b,magic);put_u16(b,e.protocol_major);put_u16(b,e.protocol_minor);put_u16(b,e.type);put_u16(b,e.flags);put_u32(b,e.payload_length);put_u64(b,e.sequence);put_guid(b,e.correlation);std::array<std::uint8_t,envelope_size>a{};std::copy(b.begin(),b.end(),a.begin());return a;}
envelope decode_envelope(std::span<const std::uint8_t>b,std::uint32_t max){if(b.size()!=envelope_size)throw protocol_error("truncated envelope");std::size_t o=0;if(get_u32(b,o)!=magic)throw protocol_error("invalid magic");envelope e;e.protocol_major=get_u16(b,o);if(e.protocol_major!=major)throw protocol_error("unsupported major");e.protocol_minor=get_u16(b,o);if(e.protocol_minor!=minor)throw protocol_error("unsupported minor");e.type=get_u16(b,o);e.flags=get_u16(b,o);if((e.flags&~1u)!=0)throw protocol_error("unsupported flags");e.payload_length=get_u32(b,o);if(e.payload_length>max)throw protocol_error("oversized payload");e.sequence=get_u64(b,o);if(e.sequence==0)throw protocol_error("zero envelope sequence");e.correlation=get_guid(b,o);return e;}
guid parse_guid(std::wstring_view text){std::wstring h;for(auto c:text)if(c!=L'-'&&c!=L'{'&&c!=L'}')h.push_back(c);if(h.size()!=32)throw protocol_error("invalid guid");guid g;for(std::size_t i=0;i<16;++i){int a=hex(h[i*2]),d=hex(h[i*2+1]);if(a<0||d<0)throw protocol_error("invalid guid");g.bytes[i]=static_cast<std::uint8_t>((a<<4)|d);}return g;}
std::vector<std::uint8_t> parse_hex(std::wstring_view text){if(text.size()%2)throw protocol_error("invalid hex");std::vector<std::uint8_t>b(text.size()/2);for(std::size_t i=0;i<b.size();++i){int a=hex(text[i*2]),d=hex(text[i*2+1]);if(a<0||d<0)throw protocol_error("invalid hex");b[i]=static_cast<std::uint8_t>((a<<4)|d);}return b;}
audio_metadata decode_audio_metadata(std::span<const std::uint8_t>b){if(b.size()!=audio_payload_size)throw protocol_error("invalid audio payload size");std::size_t o=0;audio_metadata m;m.worker_session=get_guid(b,o);m.capture_session=get_guid(b,o);m.sequence=get_i64(b,o);m.sample_index=get_i64(b,o);m.timestamp_ms=get_i64(b,o);m.payload_length=get_u32(b,o);if(m.payload_length!=pcm_bytes)throw protocol_error("invalid pcm size");return m;}
bool validate_audio(stream_statistics&s,const audio_metadata&m){if(m.worker_session!=s.worker_session||m.capture_session!=s.capture_session||m.sequence<1||m.sample_index<0||m.timestamp_ms<=0||m.payload_length!=pcm_bytes)return false;std::int64_t gap=0;if(s.frames){if(m.sequence<=s.last_sequence||m.timestamp_ms<s.last_timestamp)return false;auto delta=m.sequence-s.last_sequence;if(m.sample_index!=s.last_sample_index+delta*320)return false;gap=delta-1;}else{if(m.sequence!=s.initial_sequence||m.sample_index!=0)return false;}auto next=s;if(!next.frames){next.first_sequence=m.sequence;next.first_timestamp=m.timestamp_ms;}next.frames++;next.bytes+=pcm_bytes;next.last_sequence=m.sequence;next.last_timestamp=m.timestamp_ms;next.last_sample_index=m.sample_index;next.gaps+=gap;s=next;return true;}
std::vector<std::uint8_t> encode_summary(const stream_statistics&s){std::vector<std::uint8_t>b;put_guid(b,s.capture_session);put_i64(b,s.frames);put_i64(b,s.bytes);put_i64(b,s.first_sequence);put_i64(b,s.last_sequence);put_i64(b,s.gaps);put_i64(b,s.invalid);put_i64(b,s.first_timestamp);put_i64(b,s.last_timestamp);return b;}
std::vector<std::uint8_t> encode_worker_hello(const guid&s,std::span<const std::uint8_t>nonce,std::int32_t pid,std::string_view build,std::uint64_t capabilities){if(nonce.size()!=32)throw protocol_error("invalid nonce");std::vector<std::uint8_t>b;put_guid(b,s);b.insert(b.end(),nonce.begin(),nonce.end());put_i32(b,pid);put_u16(b,0);put_u16(b,0);put_string(b,build,256);put_u64(b,capabilities);return b;}
std::vector<std::uint8_t> encode_audio_pipe_hello(const guid&s,std::span<const std::uint8_t>nonce,std::int32_t pid){if(nonce.size()!=32)throw protocol_error("invalid nonce");std::vector<std::uint8_t>b;put_guid(b,s);b.insert(b.end(),nonce.begin(),nonce.end());put_i32(b,pid);return b;}
void decode_audio_pipe_accepted(std::span<const std::uint8_t>b,const guid&s,std::int32_t pid){std::size_t o=0;if(get_guid(b,o)!=s||get_i32(b,o)!=pid||o!=b.size())throw protocol_error("invalid audio pipe acceptance");}
bool is_known_message_type(std::uint16_t raw){return(raw>=static_cast<std::uint16_t>(message_type::worker_hello)&&raw<=static_cast<std::uint16_t>(message_type::audio_pipe_accepted))||raw==static_cast<std::uint16_t>(message_type::audio_frame);}
bool is_optional_unknown(std::uint16_t raw,std::uint16_t flags){if(is_known_message_type(raw))return false;if((flags&1u)!=0)return true;throw protocol_error("unknown required message");}
void accept_sequence(std::uint64_t&last,std::uint64_t candidate){if(candidate==0||candidate<=last)throw protocol_error("envelope sequence is not strictly increasing");last=candidate;}
void require_correlation(const guid&actual,const guid&expected){if(actual!=expected)throw protocol_error("correlation mismatch");}
void stream_lifecycle::start(){if(streaming)throw protocol_error("audio stream is already active");streaming=true;}
void stream_lifecycle::stop(){if(!streaming)throw protocol_error("audio stream is not active");streaming=false;}
}
